In [1]:
import sys

import plotly.express as px
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots


In [5]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [6]:
sys.path.append("../HetGNN/code_gcn/")
from data_loader import EventGraphDataset

In [8]:
dataset = EventGraphDataset(
    '../HetGNN/ProcessedData_clean/node_feature_norm.csv',
    '../HetGNN/ProcessedData_clean/graph_het_neigh_list'
)

reading node features..
done


In [11]:
dataset[0][0].shape

torch.Size([841, 7])

In [19]:
dataset[0][1].shape

torch.Size([8, 841, 10, 7])

In [35]:
import torch
a = torch.zeros(2,10,7)
b = torch.zeros(2,10,7)

b[1] = torch.ones(10, 7)
a[0] = torch.ones(10, 7)
b

tensor([[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]])

In [37]:
a_mean, b_mean = torch.mean(a, dim=1), torch.mean(b, dim=1)
a_mean, b_mean

(tensor([[1., 1., 1., 1., 1., 1., 1.],
         [0., 0., 0., 0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1., 1., 1.]]))

In [40]:
torch.cat([a_mean, b_mean], dim=1)

tensor([[1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.]])

In [43]:
a = torch.zeros(2,10)
torch.mean(a, 0)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])