In [1]:
%load_ext autoreload
%autoreload 2


# Dataset

In [1]:
from data_loader_cmu import CMUGraphDataset
dataset = CMUGraphDataset()

Reading Relation Type File: a_a_list.txt


KeyboardInterrupt: 

In [39]:
dataset.graph_edge_embedding[0][0]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 3., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 2., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

In [17]:
import pandas as pd
node_features = pd.read_csv(f'{dataset.data_root_path}/incoming_edge_embedding.csv')

In [18]:
node_features

graph-id  destination-id  e_p  e_j     e_t  e_u  e_q  e_n  e_v  e_C  \
0               0               0  0.0  0.0  1240.0  0.0  0.0  1.0  0.0  0.0   
1               0            5533  0.0  0.0     0.0  0.0  0.0  1.0  0.0  0.0   
2               0            5532  0.0  0.0     0.0  0.0  0.0  1.0  0.0  0.0   
3               0            5531  0.0  0.0     0.0  0.0  0.0  1.0  0.0  0.0   
4               0            5530  0.0  0.0     0.0  0.0  0.0  1.0  0.0  0.0   
...           ...             ...  ...  ...     ...  ...  ...  ...  ...  ...   
5046273       599         5038503  0.0  0.0     0.0  3.0  0.0  0.0  0.0  0.0   
5046274       599         5038504  0.0  0.0     0.0  3.0  0.0  0.0  0.0  0.0   
5046275       599         5038505  0.0  0.0     0.0  3.0  0.0  0.0  0.0  0.0   
5046276       599         5038499  0.0  0.0     0.0  3.0  0.0  0.0  0.0  0.0   
5046277       599         5037745  0.0  0.0     0.0  1.0  0.0  0.0  0.0  0.0   

         ...  e_H  e_w  e_r  e_A  e_z  e_y  e_i  e_B  e_x  e_D  
0        ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1        ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2        ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3        ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4        ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
5046273  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
5046274  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
5046275  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
5046276  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
5046277  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5046278 rows x 28 columns]

In [44]:
cond = (node_features['destination-id'] == 6830) & (node_features['graph-id'] == 0)
node_features[cond].values[:,2:][0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:

with open(f'{dataset.data_root_path}/a_a_list.txt', 'r') as fin:
    cnt = 0
    line = fin.readline()
    while line:
        part_ = line.strip().split(':')
        gid = int(part_[0])
        src_id = int(part_[1])
        neigh_list = [int(i) for i in part_[2].split(',')]
        line = fin.readline()
        cnt += 1
        break

In [28]:
dataset.graph_edge_embedding.shape

(600, 12, 26)

# PPR

In [2]:
import torch
from torch_geometric.data import Data, Batch
from subgraph import Subgraph
from ppr import PPR
from data_loader import HetGCNEventGraphDataset

In [3]:
data_root_dir = '../ProcessedData_HetGCN'
ppr_path = f'../ProcessedData_HetGCN/ppr_neighbours/ppr'

In [4]:
dataset = HetGCNEventGraphDataset(
                    node_feature_csv=f'{data_root_dir}/node_feature_norm.csv',
                    edge_index_csv=f'{data_root_dir}/edge_index.csv',
                    node_type_txt=f'{data_root_dir}/node_types.txt',
                    ignore_weight=True,
                    include_edge_type=True
                )

reading node features..
reading edge index..
Ignore Edge Weights.
read node types ..
node types txt: 132485
done


In [5]:
node_feature, edge_index, (_, edge_type), node_types = dataset[101237]

In [6]:
node_feature.shape

torch.Size([580, 7])

In [39]:
ppr = PPR(101237, node_feature, edge_index, n_order=10)

In [8]:
# ppr.adj_mat.toarray()[306, 456]

In [40]:
ppr.search_all(580, ppr_path)

Exists neighbor file


{0: array([0], dtype=int32),
 1: array([1], dtype=int32),
 2: array([  2, 192, 309], dtype=int32),
 3: array([3], dtype=int32),
 4: array([4], dtype=int32),
 5: array([5], dtype=int32),
 6: array([6], dtype=int32),
 7: array([  7, 195], dtype=int32),
 8: array([  8, 287, 325], dtype=int32),
 9: array([9], dtype=int32),
 10: array([10], dtype=int32),
 11: array([11], dtype=int32),
 12: array([12], dtype=int32),
 13: array([ 13, 291], dtype=int32),
 14: array([ 14, 196, 211], dtype=int32),
 15: array([15], dtype=int32),
 16: array([16], dtype=int32),
 17: array([17], dtype=int32),
 18: array([18], dtype=int32),
 19: array([ 19, 261], dtype=int32),
 20: array([ 20, 323, 219, 289, 240, 217], dtype=int32),
 21: array([21], dtype=int32),
 22: array([22], dtype=int32),
 23: array([23], dtype=int32),
 24: array([24], dtype=int32),
 25: array([25], dtype=int32),
 26: array([ 26, 262, 229], dtype=int32),
 27: array([ 27, 352], dtype=int32),
 28: array([28], dtype=int32),
 29: array([ 29, 264, 22

In [70]:
ppr.search(237)

array([237, 314], dtype=int32)

In [11]:
# ppr.P.toarray()[456,306]

In [12]:
# ppr.search(840)

In [13]:
# edge_index[0][edge_index[0] == 0], edge_index[1][edge_index[0] == 0]

In [14]:
# ppr.search_all(841, path=)


In [55]:
cond = (edge_index[0] == 306) & (
                    sum(edge_index[1] == k for k in [456]).bool()
)
# edge_index[0][sum(edge_index[0] == k for k in [265]).bool()], edge_index[1][sum(edge_index[0] == k for k in [265]).bool()]



edge_index[0][edge_index[0] == 306], edge_index[1][edge_index[0] == 306]
# edge_index[0][edge_index[0] == 3], edge_index[1][edge_index[1] == 306]

(tensor([306], device='cuda:0'), tensor([311], device='cuda:0'))

In [ ]:
# TODO: regen 103245

In [80]:
!ls ../ProcessedData_HetGCN/ppr_neighbours/ppr_neighbor103245.pt
!ls ../ProcessedData_HetGCN/ppr_subgraphs/ppr_subgraph103245.pt

!rm ../ProcessedData_HetGCN/ppr_neighbours/ppr_neighbor103245.pt
!rm ../ProcessedData_HetGCN/ppr_subgraphs/ppr_subgraph103245.pt

../ProcessedData_HetGCN/ppr_neighbours/ppr_neighbor101237.pt
ls: cannot access ../ProcessedData_HetGCN/ppr_subgraphs/ppr_subgraph101237.pt: No such file or directory
rm: cannot remove ‘../ProcessedData_HetGCN/ppr_subgraphs/ppr_subgraph101237.pt’: No such file or directory


In [124]:
subgraph = Subgraph(103245, None, None, subgraph_path="../ProcessedData_HetGCN/ppr_subgraphs/ppr")
subgraph.build()

In [125]:
subgraph.search([0,3,4,9,5,11])

(DataDataBatch(x=[12, 7], edge_index=[2, 12], edge_attr=[12], pos=[12], batch=[12], ptr=[7]),
 tensor([ 0,  3,  4,  7,  9, 10]))

In [134]:
15000 * 6, 15000 * 7

(90000, 105000)

In [126]:
# subgraph = Subgraph(103245, dataset[103245], ppr_path, 100, 10, subgraph_path="../ProcessedData_HetGCN/ppr_subgraphs/ppr")


In [127]:
# subgraph.build()

In [128]:
# row, col = edge_index
# row[(row == 309) & (col == 192)], col[(row == 309) & (col == 192)]

In [129]:
# torch.cuda.empty_cache()
sample_idx = [266, 20, 24, 569, 299, 228, 782, 717, 338, 520, 741, 208, 216, 41, 585, 435, 534, 697, 693, 450, 591, 571, 445, 329, 611, 507, 533, 421, 462, 451, 312, 455, 688, 500, 426, 777, 704, 560, 196, 726, 505, 794, 618, 510, 822, 824, 460, 422, 601, 414, 690, 121, 700, 324, 600, 562, 151, 398, 2, 805, 580, 607, 809, 606, 657, 177, 759, 236, 75, 829, 96, 734, 366, 798, 515, 466, 468, 684, 164, 306, 71, 199, 801, 279, 542, 590, 52, 803, 360, 141, 707, 355, 667, 493, 168, 558, 557, 200, 16, 723]



In [130]:
x_, index_ = subgraph.search(sample_idx)
x_

DataDataBatch(x=[295, 7], edge_index=[2, 438], edge_attr=[438], pos=[295], batch=[295], ptr=[101])

In [104]:
x_.edge_attr

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
        0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 2, 2, 0, 1, 1, 1, 1, 1, 0, 1, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 1, 1, 0, 0, 0, 0, 2, 0, 2, 0, 1, 2, 2, 1, 0, 0, 0, 0, 0, 2, 2, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 2, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 2, 0, 0,
        0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 2, 0, 1, 2, 1, 0, 0, 1, 0, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 2,
        2, 2, 0, 2, 0, 2, 0, 1, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
        2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,

In [114]:
x_.edge_index

tensor([[1, 2, 4, 5, 6, 7, 8, 9],
        [2, 1, 5, 4, 7, 6, 9, 8]])

In [116]:
x_.batch

tensor([0, 1, 1, 2, 3, 3, 4, 4, 5, 5])

In [102]:
x_.pos

tensor([0, 5, 4, 2, 3, 4])

In [58]:
x_.x

tensor([[ 2.3552e-04,  2.6773e-04, -1.8384e-05,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  2.6262e-04],
        [ 2.2004e-04,  2.6773e-04,  2.3899e-04,  3.1070e-08,  5.1565e-05,
          1.4681e-06,  2.1675e-04],
        [ 2.2165e-04,  1.4416e-04,  7.3536e-05,  2.1438e-06,  1.0313e-04,
          1.8645e-04,  2.2148e-04],
        [ 2.2036e-04,  2.0595e-05,  7.3536e-05,  2.9206e-06,  0.0000e+00,
          1.8938e-04,  2.1769e-04],
        [ 2.2036e-04,  8.2378e-05,  7.3536e-05,  2.9724e-06,  5.1565e-05,
          1.6002e-04,  2.1801e-04],
        [ 4.6782e-06,  1.8535e-04,  2.3899e-04,  6.3486e-06,  2.0626e-04,
          2.6426e-04,  4.5714e-06],
        [ 2.2149e-04,  1.2357e-04,  1.1030e-04,  6.2761e-06,  2.5782e-04,
          3.2885e-04,  2.2116e-04],
        [ 2.3552e-04,  2.6773e-04, -1.8384e-05,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  2.6262e-04],
        [ 2.3552e-04,  2.6773e-04, -1.8384e-05,  9.5488e-06,  1.0313e-04,
          0.0000e+00,  2.6278e-04],
        [ 

In [45]:
Batch().from_data_list([subgraph.subgraph[3], subgraph.subgraph[0]]).edge_index

tensor([[0, 1, 1, 2, 2, 3, 3, 4],
        [3, 4, 2, 3, 1, 0, 2, 1]])

In [63]:
dataset.node_feature_df['trace_id'].unique()

array([     0,      1,      2, ..., 132482, 132483, 132484])

In [12]:
import multiprocessing as mp

with mp.Pool() as pool:
    list(
        pool.imap_unordered(
            process_ppr(dataset), list(range(1000)), chunksize=1000
        )
    )

RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

In [11]:
def process_ppr(dataset, gid):
    x, edge_index, (_, edge_type), node_types = dataset[gid]
    ppr = PPR(gid, x, edge_index, n_order=10)
    ppr.search_all(x.shape[0], ppr_path)

In [127]:
from tqdm import tqdm

ppr_path = f'../ProcessedData_HetGCN/ppr_neighbours/ppr'

for gid in tqdm(range(13, 132485)):
#     subgraph = Subgraph(gid, dataset[gid], ppr_path, 100, 10)
#     subgraph.build()
    x, edge_index, (_, edge_type), node_types = dataset[gid]
    ppr = PPR(gid, x, edge_index, n_order=10)
    ppr.search_all(x.shape[0], ppr_path)

  0%|          | 28/132472 [01:37<128:12:00,  3.48s/it]


KeyboardInterrupt: 